#!/bin/bash

# exit if any command in this script fails
set -e

# enable bash debugging
set -x

set -o pipefail

echo "Deploying docs apps"

cp -r "/opt/deploy/docs-dev.conf" "/etc/supervisor/conf.d/docs-dev.conf"

supervisord -n -c /etc/supervisor/supervisord.conf
